import React, { useEffect } from "react";
import Head from "next/head";

// layout
import Layout from "../../../common/layouts/Layout";
import {
  setActiveTab,
  setActiveIPOTab,
} from "../../../store/stockIndices/StockIndicesSlice";

// redux
import { useDispatch } from "react-redux";

// container
import StocksIndicesLayout from "../../../containers/stocksindices/StocksIndicesLayout";

// component
import TopTab3 from "../../../common/component/stocksindices/top-tab3/TopTab3";
import Upcoming from "../../../common/component/stocksindices/tabs/tab3/upcoming/Upcoming";

const UpcomingPage = () => {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(setActiveTab(2));
    dispatch(setActiveIPOTab(0));
  }, []);

  return (
    <Layout>
      <StocksIndicesLayout>
        <Head>
          <title>Stock Indices | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="tab3">
          <div className="left">
            <TopTab3 />
            <div className="container">
              <Upcoming />
            </div>
          </div>
        </div>
      </StocksIndicesLayout>
    </Layout>
  );
};

export default UpcomingPage;
