import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import { setActiveHelpTab } from "../../../store/help/HelpSlice";

// component
import DemoVideo from "../../../common/component/help/demoVideo/DemoVideo";
import SystemUpdate from "../../../common/component/help/systemUpdate/SystemUpdate";
import RaiseTicket from "../../../common/component/help/raiseTicket/RaiseTicket";

import { ComponentShield } from "next-shield";

const Help = () => {
  const theme = useSelector((state) => state.Common.theme);
  const router = useRouter();
  const { tab } = router.query;
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const Tabs = useSelector((state) => state.Help.HelpTabs);
  const activeTab = useSelector((state) => state.Help.activeHelpTab);

  useEffect(() => {
    Tabs.forEach((item, i) => {
      if (tab == item.slug) {
        dispatch(setActiveHelpTab(item.id));
      }
    });
  }, [tab]);

  const _changeTab = (id, slug) => {
    router.push(`/help/${slug}`);
    dispatch(setActiveHelpTab(id));
  };

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>Help | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`help ${theme}`}>
          <div className="help_top">
            <div className="left">
              <div className={`secondary_tabs ${theme}`}>
                {Tabs.map((item, i) => (
                  <div
                    key={i}
                    className={`secondary_tabs-item ${
                      activeTab == item.id && "focused"
                    }`}
                    onClick={() => {
                      _changeTab(item.id, item.slug);
                    }}
                  >
                    {item.name}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className={`help_bottom ${theme}`}>
            {activeTab == 0 && <DemoVideo />}
            {activeTab == 1 && <RaiseTicket />}
            {activeTab == 2 && <SystemUpdate />}
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Help;
