import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import {
  setActiveTab,
  setActiveInfoTab,
} from "../../../store/stockIndices/StockIndicesSlice";

// container
import StocksIndicesLayout from "../../../containers/stocksindices/StocksIndicesLayout";

// component
import TopTab from "../../../common/component/stocksindices/top-tab/TopTab";
import Announcement from "../../../common/component/stocksindices/tabs/tab1/announcement/Announcement";
import Sider from "../../../common/component/stocksindices/tabs/tab1/news/sider/Sider";

const announcements = () => {
  const theme = useSelector((state) => state.Common.theme);
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const Tabs = useSelector((state) => state.StockIndices.tabs);
  const activeTab = useSelector((state) => state.StockIndices.activeTab);
  const activeInfoTab = useSelector((state) => state.StockIndices.activeTab);

  useEffect(() => {
    dispatch(setActiveTab(0));
    dispatch(setActiveInfoTab(1));
  }, []);

  return (
    <Layout>
      <StocksIndicesLayout>
        <Head>
          <title>Stock Indices | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="tab1">
          <div className="left">
            <TopTab />
            <div className="container">
              <Announcement />
            </div>
          </div>
          <div className="side">
            {(activeInfoTab == 0 || activeInfoTab == 1) && <Sider />}
          </div>
        </div>
      </StocksIndicesLayout>
    </Layout>
  );
};

export default announcements;
