import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import { setActiveTab } from "../../../store/heatmap/HeatmapSlice";

// containers
import TabSection from "../../../common/component/tabSections/TabSections";
import HeatmapAdvanceDecline from "../../../common/component/heatmap/heatmapAdvanceDecline/HeatmapAdvanceDecline";

const Heatmap = () => {
  const theme = useSelector((state) => state.Common.theme);
  const router = useRouter();
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const Tabs = useSelector((state) => state.Heatmap.tabs);
  const activeTab = useSelector((state) => state.Heatmap.activeTab);

  useEffect(() => {
    dispatch(setActiveTab(2));
  }, []);

  const _chnageTab = (slug, id) => {
    if (activeTab !== id) {
      dispatch(setActiveTab(id));
      router.push(`/${globalTabs[2].link}/${slug}`);
    }
  };

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>Heatmap | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${theme} Heatmap`}>
          <div className="Heatmap_top">
            <div className="left">
              <div className={`secondary_tabs ${theme}`}>
                {Tabs.map((item, i) => (
                  <div
                    key={i}
                    className={`secondary_tabs-item ${
                      activeTab == item.id && "focused"
                    }`}
                    onClick={() => {
                      _chnageTab(item.slug, item.id);
                    }}
                  >
                    {item.name}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className="Heatmap_bottom">
            <TabSection headerLable={`Heatmap`}>
              <HeatmapAdvanceDecline />
            </TabSection>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  };
}

export default Heatmap;
