[functions]

  [functions._ipx]
  node_bundler = "nft"

  [functions.___netlify-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions.___netlify-odb-handler]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

  [functions."_api_*"]
  included_files = [
    ".env",
    ".env.local",
    ".env.production",
    ".env.production.local",
    "./public/locales/**",
    "./next-i18next.config.js",
    ".next/server/**",
    ".next/serverless/**",
    ".next/*.json",
    ".next/BUILD_ID",
    ".next/static/chunks/webpack-middleware*.js",
    "!.next/server/**/*.js.nft.json",
    "!.next/server/**/*.map",
    "!**/node_modules/@next/swc*/**/*",
    "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
    "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
    "!node_modules/next/dist/compiled/webpack/bundle4.js",
    "!node_modules/next/dist/compiled/webpack/bundle5.js"
  ]
  external_node_modules = []
  node_bundler = "nft"

[build]
command = "npm run build"
publish = ".next"

  [build.environment]
  NEXT_PRIVATE_TARGET = "server"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 200

[[redirects]]
from = "/_next/image*"
to = "/_ipx/w_:width,q_:quality/:url"
status = 301

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/builders/_ipx"
status = 200

[[redirects]]
from = "/cache/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/server/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/serverless/*"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/trace"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/traces"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/routes-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/build-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/prerender-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/react-loadable-manifest.json"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/BUILD_ID"
to = "/404.html"
status = 404
force = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/favicon.ico"
to = "/favicon.ico"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icon-192x192.png"
to = "/icon-192x192.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icon-256x256.png"
to = "/icon-256x256.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icon-384x384.png"
to = "/icon-384x384.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/icon-512x512.png"
to = "/icon-512x512.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/index.html"
to = "/index.html"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/logo192.png"
to = "/logo192.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/logo512.png"
to = "/logo512.png"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/manifest.json"
to = "/manifest.json"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/vercel.svg"
to = "/vercel.svg"
status = 200

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200
force = true

  [redirects.conditions]
  Cookie = [
    "__prerender_bypass",
    "__next_preview_data"
  ]

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/index.json"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/"
to = "/.netlify/builders/___netlify-odb-handler"
status = 200
force = true

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/diffusion-indicators.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/diffusion-indicators"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/heatmap.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/heatmap"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/participants-data.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/participants-data"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/scanners.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/scanners"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/sentiment-indicators.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/sentiment-indicators"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/stocks-indices.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/stocks-indices"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/_next/data/-kCNuzL0CgLq_2vfCeTpz/:tabname.json"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/:tabname"
to = "/.netlify/functions/___netlify-handler"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/___netlify-handler"
status = 200

[context]

  [context.production]

    [context.production.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.production.functions]

      [context.production.functions._ipx]
      node_bundler = "nft"

      [context.production.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.production.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.production.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.production.build]

      [context.production.build.environment]
      NEXT_PRIVATE_TARGET = "server"

  [context.v2]

    [context.v2.environment]
    NEXT_PRIVATE_TARGET = "server"

    [context.v2.functions]

      [context.v2.functions._ipx]
      node_bundler = "nft"

      [context.v2.functions.___netlify-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.v2.functions.___netlify-odb-handler]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

      [context.v2.functions."_api_*"]
      included_files = [
        ".env",
        ".env.local",
        ".env.production",
        ".env.production.local",
        "./public/locales/**",
        "./next-i18next.config.js",
        ".next/server/**",
        ".next/serverless/**",
        ".next/*.json",
        ".next/BUILD_ID",
        ".next/static/chunks/webpack-middleware*.js",
        "!.next/server/**/*.js.nft.json",
        "!.next/server/**/*.map",
        "!**/node_modules/@next/swc*/**/*",
        "!node_modules/next/dist/compiled/@ampproject/toolbox-optimizer/**/*",
        "!node_modules/next/dist/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/next-server/server/lib/squoosh/**/*.wasm",
        "!node_modules/next/dist/compiled/webpack/bundle4.js",
        "!node_modules/next/dist/compiled/webpack/bundle5.js"
      ]
      external_node_modules = []
      node_bundler = "nft"

    [context.v2.build]

      [context.v2.build.environment]
      NEXT_PRIVATE_TARGET = "server"