import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import { setActiveHelpTab } from "../../../store/help/HelpSlice";
import { addUserDefineTab } from "../../../store/common/CommonSlice";

// component
import SystemUpdate from "../../../common/component/help/systemUpdate/SystemUpdate";

const SystemUpdatePage = () => {
  const { theme, GlobalTabs } = useSelector((state) => state.Common);
  const router = useRouter();
  const dispatch = useDispatch();
  const Tabs = useSelector((state) => state.Help.HelpTabs);
  const activeTab = useSelector((state) => state.Help.activeHelpTab);

  const _changeTab = (id, slug) => {
    router.push(`/help/${slug}`);
    dispatch(setActiveHelpTab(id));
  };

  useEffect(() => {
    let isHelpOpen = GlobalTabs.some((item) => item.name === "Help");
    dispatch(setActiveHelpTab(2));
    if (!isHelpOpen) {
      dispatch(
        addUserDefineTab({
          name: "Help",
          link: `help`,
          userDefined: true,
        })
      );
    }
  }, []);

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>Help | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`help ${theme}`}>
          <div className="help_top">
            <div className="left">
              <div className={`secondary_tabs ${theme}`}>
                {Tabs.map((item, i) => (
                  <div
                    key={i}
                    className={`secondary_tabs-item ${
                      activeTab == item.id && "focused"
                    }`}
                    onClick={() => {
                      _changeTab(item.id, item.slug);
                    }}
                  >
                    {item.name}
                  </div>
                ))}
              </div>
            </div>
          </div>
          <div className={`help_bottom ${theme}`}>{<SystemUpdate />}</div>
        </div>
      </div>
    </Layout>
  );
};

export default SystemUpdatePage;
