import React from "react";
import Head from "next/head";

// layout
import Layout from "../../common/layouts/Layout";

// redux
import { useSelector } from "react-redux";

// containers
import SentimentIndicatorsLayout from "../../containers/sentimentIndicators/sentimentIndicatorsLayout/SentimentIndicatorsLayout";

const SentimentIndicators = () => {
  const theme = useSelector((state) => state.Common.theme);

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>Sentiment Indicators | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SentimentIndicatorsLayout />
      </div>
    </Layout>
  );
};

export default SentimentIndicators;
