import React, { useEffect, useState } from "react";
import Head from "next/head";
import dayjs from "dayjs";
// layout
import Layout from "../../../common/layouts/Layout";
import {
  setActiveTab,
  setActiveCalendarInnerTab,
} from "../../../store/stockIndices/StockIndicesSlice";

// redux
import { useDispatch, useSelector } from "react-redux";
import { handleChangeData } from "../../../store/calendar/CalendarSlice";

// container
import StocksIndicesLayout from "../../../containers/stocksindices/StocksIndicesLayout";

// component
import Search from "../../../common/component/search/Search";
import TopTab4 from "../../../common/component/stocksindices/top-tab4/TopTab4";
import CalendarLayout from "../../../common/component/stocksindices/tabs/tab4/calendarLayout/CalendarLayout";

//graphql
import { useQuery } from "@apollo/client";
import { GET_CUSTOMER_TICKETS } from "../../../gql/queries";

import { useUserData } from "@nhost/nextjs";

const MyTickets = () => {
  const dispatch = useDispatch();
  const { daterange } = useSelector((state) => state.Calendar);

  const [value, setValue] = useState("");

  const userData = useUserData();

  useEffect(() => {
    dispatch(setActiveTab(3));
    dispatch(setActiveCalendarInnerTab(3));
  }, []);

  useQuery(GET_CUSTOMER_TICKETS, {
    variables: {
      order_by: { created_at: "asc" },
      where: {
        _and: [
          {
            customer_id: { _eq: userData?.id },
          },
          {
            created_at: { _gte: dayjs(daterange[0]).format("YYYY-MM-DD") },
          },
          {
            created_at: {
              _lte: dayjs(daterange[daterange.length - 2]).format("YYYY-MM-DD"),
            },
          },
          {
            title: {
              _ilike: `%${value}%`,
            },
          },
        ],
      },
    },
    onCompleted: (data) => {
      if (Array.isArray(data?.indiacharts_customer_tickets)) {
        dispatch(
          handleChangeData({
            key: "myTickets",
            value: data.indiacharts_customer_tickets.map((d) => {
              return {
                title: `#${d.uid}`,
                subTitle: d.title,
                date: dayjs(d.created_at).format("YYYY-MM-DD"),
                payload: d,
              };
            }),
          })
        );
      }
    },
  });

  return (
    <Layout>
      <StocksIndicesLayout>
        <Head>
          <title>Stock Indices | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="tab4">
          <div className="left">
            <div className="left_headersearch">
              <h1>CALENDAR</h1>
              <div>
                <Search
                  placeholderText={"Enter Keyword"}
                  onChange={(e) => setValue(e.target.value)}
                />
              </div>
            </div>
          </div>
          <div className="content">
            <TopTab4 />
            <div className="right">
              <CalendarLayout page="myTickets" />
            </div>
          </div>
        </div>
      </StocksIndicesLayout>
    </Layout>
  );
};

export default MyTickets;
