import React from "react";
import Head from "next/head";

// layout
import Layout from "../../common/layouts/Layout";

// redux
import { useSelector } from "react-redux";

// containers
import ScannersLayout from "../../containers/scanners/scannersLayout/ScannersLayout";

const Scanners = () => {
  const theme = useSelector((state) => state.Common.theme);

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>Scanners | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ScannersLayout />
      </div>
    </Layout>
  );
};

export default Scanners;
