import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";

// layout
import Layout from "../../../common/layouts/Layout";
import {
  setActiveTab,
  setActiveIPOTab,
} from "../../../store/stockIndices/StockIndicesSlice";

// redux
import { useSelector, useDispatch } from "react-redux";

// container
import StocksIndicesLayout from "../../../containers/stocksindices/StocksIndicesLayout";

// component
import TopTab3 from "../../../common/component/stocksindices/top-tab3/TopTab3";
import Ongoing from "../../../common/component/stocksindices/tabs/tab3/ongoing/Ongoing";

const ongoing = () => {
  const theme = useSelector((state) => state.Common.theme);
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const Tabs = useSelector((state) => state.StockIndices.tabs);
  const activeTab = useSelector((state) => state.StockIndices.activeTab);
  const activeInfoTab = useSelector((state) => state.StockIndices.activeTab);

  useEffect(() => {
    dispatch(setActiveTab(2));
    dispatch(setActiveIPOTab(1));
  }, []);

  return (
    <Layout>
      <StocksIndicesLayout>
        <Head>
          <title>Stock Indices | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="tab3">
          <div className="left">
            <TopTab3 />
            <div className="container">
              <Ongoing />
            </div>
          </div>
        </div>
      </StocksIndicesLayout>
    </Layout>
  );
};

export default ongoing;
