import React, { useState, useEffect, useRef, useMemo } from "react";
import Head from "next/head";
import { useScreenshot, createFileName } from "use-react-screenshot";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import {
  setActiveTab,
  setActiveStocksTab,
} from "../../../store/stockIndices/StockIndicesSlice";

// container
import StocksIndicesLayout from "../../../containers/stocksindices/StocksIndicesLayout";

// component
import StocksHeader from "../../../common/component/stocksindices/tabs/stocks/header/StocksHeader";
import StocksInfo from "../../../common/component/stocksindices/tabs/stocks/overview/info/StocksInfo";
import StocksBusinessOverview from "../../../common/component/stocksindices/tabs/stocks/overview/businessOverview/StocksBusinessOverview";
import StocksPricePerformance from "../../../common/component/stocksindices/tabs/stocks/overview/pricePerformance/StocksPricePerformance";
import StocksSeasonality from "../../../common/component/stocksindices/tabs/stocks/overview/seasonality/StocksSeasonality";
import StocksPattern from "../../../common/component/stocksindices/tabs/stocks/overview/pattern/StocksPattern";

const news = () => {
  const theme = useSelector((state) => state.Common.theme);
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const Tabs = useSelector((state) => state.StockIndices.tabs);
  const ActiveTab = useSelector((state) => state.StockIndices.activeTab);
  const InnerTabs = useSelector((state) => state.StockIndices.innerTabs);
  const ActiveStocksTab = useSelector(
    (state) => state.StockIndices.activeStocksTab
  );
  
  // screenshot
  const [image, takeScreenShot] = useScreenshot({
    type: "image/png",
    quality: 1.0,
  });
  const download = (
    image,
    { name = "future activity", extension = "png" } = {}
  ) => {
    const a = document.createElement("a");
    a.href = image;
    a.download = createFileName(extension, name);
    a.click();
  };
  const _downloadScreenshot = () => takeScreenShot(ref.current).then(download);

  // maximize screen
  const _maximize = () => {};

  const _minimize = () => {};

  useEffect(() => {
    dispatch(setActiveTab(1));
    dispatch(setActiveStocksTab(0));
  }, []);

  return (
    <Layout>
      <StocksIndicesLayout>
        <Head>
          <title>Stock Indices | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="stockIndicesStocks">
          <StocksHeader />
          <div className="stockIndicesStocks_bottom">
            <StocksInfo />
            <div className="stockIndicesStocks_bottom-row">
              <StocksBusinessOverview />
              <StocksPricePerformance />
            </div>
            <div className="stockIndicesStocks_bottom-row">
              <StocksSeasonality />
              <StocksPattern />
            </div>
          </div>
        </div>
      </StocksIndicesLayout>
    </Layout>
  );
};

export default news;
