import React, { useState, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Slider from "rc-slider";
import Modal from "react-modal";

// layout
import Layout from "../../../common/layouts/Layout";

// redux
import { useSelector, useDispatch } from "react-redux";
import {
  setActiveParticipantsDataTab,
  setActiveParticipantsDataScreen,
} from "../../../store/participantsData/ParticipantsDataSlice";

// apollo
import { initializeApollo } from "../../../gql/apolloClient";
import { useQuery } from "@apollo/client";
// import { GET_FII_DATES } from "../../../gql/queries";

// containers
import Buttom from "../../../common/component/button/Button";
import DropDown from "../../../common/component/dropDown/DropDown";
import ParticipantsCashMarket from "../../../common/component/participants/cashmarket/ParticipantsCashMarket";
import ParticipantsDerivatives from "../../../common/component/participants/derivatives/ParticipantsDerivatives";

const ParticipantsDataView = () => {
  const theme = useSelector((state) => state.Common.theme);
  const router = useRouter();
  const { tab, view } = router.query;
  const dispatch = useDispatch();
  const globalTabs = useSelector((state) => state.Common.GlobalTabs);
  const [modalIsOpen, setIsOpen] = useState(true);
  const Tabs = useSelector(
    (state) => state.ParticipantsData.ParticipantsDataTabs
  );
  const screens = useSelector(
    (state) => state.ParticipantsData.ParticipantsDataScreens
  );
  const activeTab = useSelector(
    (state) => state.ParticipantsData.activeParticipantsDataTab
  );
  const activeScreen = useSelector(
    (state) => state.ParticipantsData.activeParticipantsDataScreen
  );
  const [selectedDate, setSelectedDate] = useState("");
  const [submitted, setSubmitted] = useState("");
  const [filterState, setFilterState] = useState(0);
  // const { data } = useQuery(GET_FII_DATES, {
  //   onCompleted: (data) => {
  //     setSelectedDate(data?.dates?.[0]?.priced_date);
  //     setSubmitted(data?.dates?.[0]?.priced_date);
  //   },
  // });

  // const dates = data?.dates?.map((d) => d?.priced_date);

  useEffect(() => {
    Tabs.forEach((item, i) => {
      if (tab == item.slug) {
        dispatch(setActiveParticipantsDataTab(item.id));
      }
    });
    // console.log(tab, view);
  }, [tab]);

  useEffect(() => {
    screens.forEach((item, i) => {
      if (view == item.slug) {
        dispatch(setActiveParticipantsDataScreen(item.id));
      }
    });
  }, [view]);

  const _chnageTab = (slug, id) => {
    dispatch(setActiveParticipantsDataTab(id));
    if (id == 0) {
      router.push(
        `/${globalTabs[5].link}/${slug}/${screens[activeScreen].slug}`
      );
    } else {
      router.push(`/${globalTabs[5].link}/${slug}`);
    }
  };

  return (
    <Layout>
      <div className={`tabs-body ${theme}`}>
        <Head>
          <title>FII/DII Participants Data | IC Trading</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${theme} Participatns`}>
          <div className="Participatns_top">
            <div className="left">
              <div className={`secondary_tabs ${theme}`}>
                {Tabs.map((item, i) => (
                  <div
                    key={i}
                    className={`secondary_tabs-item ${
                      activeTab == i && "focused"
                    }`}
                    onClick={() => {
                      _chnageTab(item.slug, item.id);
                    }}
                  >
                    {item.name}
                  </div>
                ))}
              </div>
            </div>
            {activeTab == 0 && (
              <div className="viewBy">
                <p>View By</p>
                <div className="viewBy-slider">
                  <Slider
                    min={0}
                    defaultValue={16}
                    marks={{
                      0: `Daily`,
                      50: `Monthly`,
                      100: `Yearly`,
                    }}
                    step={null}
                    onChange={(v) => setFilterState(v)}
                  />
                </div>
              </div>
            )}
          </div>
          <div className="Participatns_bottom">
            {activeTab == 0 && (
              <>
                <Modal
                  isOpen={modalIsOpen}
                  contentLabel="Fullscreen_Modal"
                  className={`FullView_Modal v2 ${theme}`}
                  overlayClassName="FullView_Modal_Overlay v2"
                  ariaHideApp={false}
                >
                  <ParticipantsCashMarket
                    name={screens[activeScreen].name}
                    fullScreen
                    filterstate={filterState}
                    fullScreenId={screens[activeScreen].id}
                  />
                </Modal>
              </>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
};

// export async function getServerSideProps() {
//   const apolloClient = initializeApollo();

//   await apolloClient.query({
//     query: GET_FII_DATES,
//   });

//   return {
//     props: {
//       initialApolloState: apolloClient.cache.extract(),
//     },
//   };
// }

export default ParticipantsDataView;
